### ISSUE TITLE
Fix "Location" Search

### ISSUE THREAD

**Issue by TheoBr** [metpetdb/interface_v2#8] opened 2016-09-27 17:12 UTC
Location search is relatively broken and the reason for such is unclear

**Comment by tamblc** [comment] 2016-10-06 04:23
This is caused by a malformed query that is being sent to the API. The flask portion is sending empty fields which is causing a server error. I will update with specific line numbers shortly.

**Comment by kienankb** [comment] 2016-11-01 23:32
Might be due to differing unicode standards--UTF-8 vs UTF-16.  Still investigating.

**Comment by kienankb** [comment] 2016-12-13 08:47
Fixed with [PR#16](https://github.com/metpetdb/interface_v2/pull/16).

**Closed by kienankb** 2016-12-13 08:47 UTC
